/** Единый слой пользовательских текстов — деловой тон, без «черновиков». */

export const layoutCopy = {
  stripHours: 'Режим работы: пн–сб 09:00–20:00 · вс — выходной',
  stripDelivery: 'Доставка и оплата',
  stripReturns: 'Возврат',
  stripSupport: 'Служба поддержки',
  brandTag: 'автозапчасти',
  searchLabel: 'Поиск по каталогу',
  searchPlaceholder: 'Артикул, каталожный номер или наименование',
  searchSubmit: 'Искать',
  garageDefault: 'Гараж',
  cart: 'Корзина',
  drawerTitle: 'Навигация',
  drawerHome: 'Главная',
  drawerCatalog: 'Каталог',
  drawerGarage: 'Гараж',
  drawerCart: 'Корзина',
  drawerFavorites: 'Избранное',
  drawerGroupCatalog: 'Товарные группы',
  drawerGroupService: 'Сервис',
  subnavCatalog: 'Каталог',
  subnavGarage: 'Гараж',
  subnavFavorites: 'Избранное',
  footerLead:
    'Поставка оригинальных и сертифицированных автозапчастей. Подбор по VIN и каталожным номерам. Доставка по России, самовывоз со склада.',
  footerBuyers: 'Покупателям',
  footerContacts: 'Контакты',
  footerRights: 'Все права защищены',
} as const

export const homeCopy = {
  heroTitle: 'Автозапчасти для легковых автомобилей',
  heroLead:
    'Оригинальные комплектующие и проверенные аналоги. Подбор по каталожному номеру, наименованию и данным вашего автомобиля.',
  heroPlaceholder: 'Каталожный номер, артикул или наименование детали',
  heroSubmit: 'Найти в каталоге',
  heroCatalog: 'Каталог',
  heroGarage: 'Гараж',
  garageLabel: 'Активный автомобиль',
  garageUnsetTitle: 'Не задан',
  garageUnsetMeta:
    'Укажите марку, модель и модификацию — в каталоге будет доступна фильтрация по применимости к вашему авто.',
  garageCtaSet: 'Настроить',
  garageCtaEdit: 'Изменить данные',
  garageCtaClear: 'Сбросить',
  pillars: [
    { title: 'Наличие', text: 'Актуальные остатки и сроки поставки отображаются в карточке товара.' },
    { title: 'Логистика', text: 'Доставка транспортными компаниями, курьером и самовывоз со склада.' },
    { title: 'Возврат', text: 'Работаем в рамках законодательства и внутреннего регламента магазина.' },
  ],
  categoriesTitle: 'Товарные группы',
  categoriesSubtitle: 'Перейдите в раздел — откроется витрина с фильтрами по бренду, цене и наличию.',
  featuredTitle: 'Рекомендуемая подборка',
  featuredSubtitle: 'Позиции с подтверждённым складским остатком.',
  featuredLink: 'Весь каталог',
} as const

export const productUiCopy = {
  stockIn: (qty: number) => `На складе: ${qty} шт.`,
  stockOut: 'Под заказ',
  addToCart: 'В корзину',
  unavailable: 'Нет в наличии',
  addedToast: 'Позиция добавлена в корзину',
  addedToastQty: (qty: number) => `В корзину добавлено: ${qty} шт.`,
  favAdd: 'Добавлено в избранное',
  favRemove: 'Удалено из избранного',
  ariaOpenCard: (name: string) => `${name} — открыть карточку`,
  ariaFavAdd: 'Добавить в избранное',
  ariaFavRemove: 'Убрать из избранного',
  skuLine: (sku: string, oem: string) => `Артикул ${sku} · каталожный № ${oem}`,
} as const

export const catalogCopy = {
  filtersMobile: 'Фильтры и сортировка',
  filtersApply: 'Применить',
  groupCategory: 'Товарная группа',
  allItems: 'Все группы',
  brandTitle: 'Бренд',
  brandHint: 'Можно выбрать несколько значений.',
  availability: 'Наличие',
  inStockOnly: 'Только в наличии на складе',
  garageFit: 'Совместимо с автомобилем из гаража',
  garageHint: 'Сначала укажите автомобиль в разделе «Гараж».',
  priceTitle: 'Цена, ₽',
  priceFrom: 'от',
  priceTo: 'до',
  sortTitle: 'Сортировка',
  sortPopular: 'По релевантности и остатку',
  sortPriceAsc: 'Цена: по возрастанию',
  sortPriceDesc: 'Цена: по убыванию',
  sortName: 'Наименование: А—Я',
  resetFilters: 'Сбросить фильтры',
  quickTitle: 'Поиск по номеру',
  quickSub: 'Укажите каталожный номер или складской артикул в том виде, как на упаковке.',
  quickPlaceholder: 'Например 34116792227 или BRK-2048',
  quickAria: 'Каталожный номер или артикул',
  quickSubmit: 'Искать',
  emptyTitle: 'По заданным условиям позиции не найдены',
  emptyFiltered: 'Измените фильтры или перейдите в другую товарную группу.',
  emptyCategory: 'В выбранной группе нет позиций, удовлетворяющих критериям.',
  emptyAll: 'Все товарные группы',
  pageTitle: 'Каталог',
} as const

export const productPageCopy = {
  subtitle: (manufacturer: string, sku: string) => `${manufacturer} · артикул ${sku}`,
  oemLead: 'Каталожный номер (как на упаковке):',
  pillOut: 'Нет в наличии',
  favAria: 'Избранное',
  qtyLabel: 'Количество',
  addWide: 'В корзину',
  toCart: 'Перейти в корзину',
  inCartTitle: (n: number) => `В корзине: ${n} шт.`,
  syncQty: 'Подставить из корзины',
  removeLine: 'Убрать из корзины',
  sectionDesc: 'Описание',
  sectionCompat: 'Применимость (справочно)',
  specMfr: 'Производитель',
  specSku: 'Артикул',
  specOem: 'Каталожный номер',
  specStock: 'Остаток на складе',
  specStockVal: (n: number) => `${n} шт.`,
  specStockOrder: 'Под заказ',
  categoryFallback: 'Раздел',
} as const

export const searchCopy = {
  breadcrumb: 'Поиск',
  title: 'Поиск по каталогу',
  subtitleWithQuery: (q: string, n: number) => `Запрос «${q}». Найдено наименований: ${n}.`,
  subtitleEmpty: 'Введите запрос в строке поиска в шапке страницы или воспользуйтесь подсказками ниже.',
  popularLabel: 'Популярные запросы',
  garageChip: 'Гараж',
  emptyTitle: 'По запросу ничего не найдено',
  emptyText: 'Уточните формулировку либо перейдите в каталог и воспользуйтесь фильтрами.',
  toCatalog: 'Открыть каталог',
  toHome: 'На главную',
} as const

export const garagePageCopy = {
  breadcrumb: 'Гараж',
  title: 'Гараж',
  subtitle:
    'Марка, модель, год выпуска, модификация силового агрегата и при необходимости VIN. Данные используются для фильтра «совместимо с автомобилем из гаража» в каталоге.',
  labelBrand: 'Марка',
  labelModel: 'Модель',
  labelYear: 'Год выпуска',
  labelEngine: 'Двигатель / модификация',
  labelVin: 'VIN (необязательно)',
  phBrand: 'BMW',
  phModel: '3 G20',
  phEngine: '320i · 184 л.с.',
  phVin: '17 символов',
  save: 'Сохранить',
  clear: 'Очистить',
  toastNeedBrand: 'Укажите марку и модель',
  toastSaved: 'Данные автомобиля сохранены',
  toastGarageCleared: 'Гараж очищен',
  asideKicker: 'Текущий автомобиль',
  hintsNote:
    'Вводите марку и модель с клавиатуры — подсказки фильтруются по первым буквам (например «l» → Lada). Двигатель — только после выбора модели из списка.',
  modelNeedBrand: 'Сначала укажите марку',
  engineNeedModel: 'Выберите модель из подсказки — появятся варианты двигателя',
} as const

export const supportPageCopy = {
  title: 'Поддержка',
  subtitle: 'Телефон, электронная почта и форма обращения. Ответ в рабочие часы.',
  hContacts: 'Контакты',
  phoneNote: 'пн–сб 09:00–20:00',
  email: 'info@avtomagazin.ru',
  hOrder: 'По заказу',
  orderText: 'Укажите номер заказа и контактный телефон — уточним статус комплектации и отгрузки.',
  linkGarage: 'Перейти в гараж',
  formTitle: 'Обращение',
  subjectPh: 'Заказ, возврат, подбор запчастей…',
  subjectLabel: 'Тема',
  messageLabel: 'Сообщение',
  messagePh: 'Опишите вопрос',
  submit: 'Отправить',
  toastEmpty: 'Введите текст обращения',
  toastSent: 'Обращение принято. Ответим в ближайшее рабочее время.',
} as const
